services:
  web:
    image: phavane/site_sae-web:latest
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    volumes:
      # Mount the 'laravel-storage' volume to '/var/www/storage' inside the container.
      # -----------------------------------------------------------
      # This volume stores persistent data like uploaded files and cache.
      # The ':ro' option mounts it as read-only in the 'web' service because Nginx only needs to read these files.
      # The 'php-fpm' service mounts the same volume without ':ro' to allow write operations.
      # -----------------------------------------------------------
      - laravel-storage-production:/var/www/storage:ro
      - ./public:/var/www/public:ro
      - laravel-photos-production:/var/www/public:ro
    networks:
      - laravel-production
    ports:
      # Map port 80 inside the container to the port specified by 'NGINX_PORT' on the host machine.
      # -----------------------------------------------------------
      # This allows external access to the Nginx web server running inside the container.
      # For example, if 'NGINX_PORT' is set to '8080', accessing 'http://localhost:8080' will reach the application.
      # -----------------------------------------------------------
      - "${NGINX_PORT:-8000}:80"
    depends_on:
      php-fpm:
        condition: service_healthy # Wait for php-fpm health check

  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    image: phavane/site_sae-php-fpm:latest
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage # Mount the storage volume
      - laravel-photos-production:/var/www/public/storage # Mount the photos volume
    env_file:
      - .env
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    # The 'depends_on' attribute with 'condition: service_healthy' ensures that
    # this service will not start until the 'postgres' service passes its health check.
    # This prevents the application from trying to connect to the database before it's ready.
    depends_on:
      mysql:
        condition: service_healthy

#  # The 'php-cli' service provides a command-line interface for running Artisan commands and other CLI tasks.
#  # -----------------------------------------------------------
#  # This is useful for running migrations, seeders, or any custom scripts.
#  # It shares the same codebase and environment as the 'php-fpm' service.
#  # -----------------------------------------------------------
#  php-cli:
#    build:
#      context: .
#      dockerfile: ./docker/php-cli/Dockerfile
#    tty: true # Enables an interactive terminal
#    stdin_open: true # Keeps standard input open for 'docker exec'
#    env_file:
#      - .env
#    networks:
#      - laravel-production

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data-production:/var/lib/mysql
    networks:
      - laravel-production
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    networks:
      - laravel-production
    # Health check for Redis
    # -----------------------------------------------------------
    # Checks if Redis is responding to the 'PING' command.
    # This ensures that the service is not only running but also operational.
    # -----------------------------------------------------------
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpMyAdmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mysql # The hostname of the MySQL server
      PMA_USER: ${DB_USERNAME} # The username for MySQL
      PMA_PASSWORD: ${DB_PASSWORD} # The password for MySQL
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80" # Map port 80 inside the container to the port specified by 'PHPMYADMIN_PORT' on the host machine.
    networks:
      - laravel-production
    depends_on:
      - mysql

networks:
  # Attach the service to the 'laravel-production' network.
  # -----------------------------------------------------------
  # This custom network allows all services within it to communicate using their service names as hostnames.
  # For example, 'php-fpm' can connect to 'postgres' by using 'postgres' as the hostname.
  # -----------------------------------------------------------
  laravel-production:

volumes:
  mysql-data-production:
  laravel-storage-production:
  laravel-photos-production:
