apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpn-phpmyadmin
  namespace: cpn-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpn-phpmyadmin
  template:
    metadata:
      labels:
        app: cpn-phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: PMA_HOST
              value: ${DB_HOST}  # même host que pour php-fpm
            - name: PMA_PORT
              value: ${DB_PORT}  # même port que pour php-fpm
          ports:
            - containerPort: 80
