apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cpn-app

resources:
  - namespace.yaml
  - configmap/
  - deploy/
  - services/

commonAnnotations:
  managed-by: kustomize
  project: cpn-sae
  app: cpn-app
  version: v1
