- hosts: k3s_master
  gather_facts: false
  tasks:
    - name: Apply manifests app
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: "{{ item }}"
      loop:
        - k8s/

