---
- name: Create k8s directory
  file:
    path: /root/k8s
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy Kubernetes manifests
  synchronize:
    src: ../../k8s/
    dest: /root/k8s/
    delete: yes
  delegate_to: localhost

- name: Deploy with kubetctl & Kustomize
  shell: |
    kubectl apply -k /root/k8s/
  args:
    executable: /bin/bash
