; [k3s_master]
; localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

; [k3s_workers]
; # rien ici, on n’a pas de vrais nodes SSH, juste le cluster k3d dans Docker

; [k3s_cluster:children]
; k3s_master
; k3s_workers

[compose]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[compose:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=
ansible_become_password=