[k3s_master]
k3s-master ansible_host={{ lookup('env', 'K3S_MASTER_IP') }} ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_rsa

[k3s_workers]
k3s-worker1 ansible_host={{ lookup('env', 'K3S_WORKER1_IP') }} ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_rsa
k3s-worker2 ansible_host={{ lookup('env', 'K3S_WORKER2_IP') }} ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_rsa

[k3s_cluster:children]
k3s_master
k3s_workers
